spring.application.name=Agro-Shop
spring.datasource.url=jdbc:mysql://localhost:3309/database_agro_shop
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
# Forsiraj Spring da statičke fajlove traži u /static folderu
spring.web.resources.static-locations=classpath:/static/,classpath:/public/
# Ovo omogućava da Spring ne "guta" putanje do fajlova
spring.mvc.static-path-pattern=/**
